### PR TITLE
Added room join form in index page

### PR DESCRIPTION
**Pull request by MrTip0**
Added a separate area in the index page to avoid editing directly the URL

### CODE REVIEW

**Comment by jmattheis** [comment]
I'd prefer changing the create room button to something like join or create room. Then we don't need two different forms.

**Comment by MrTip0** [comment]
I edited it, now in the create form, there is the option to join the room if it already exists.

**Comment by jmattheis** [comment]
I think we don't need another check box for that. We can hardcode `joinIfExist: true` and change the label of the button to something like "join or create room".

**Review by jmattheis — APPROVED** [review]
thanks

**Pull request merged**
