### PR TITLE
Improve chrome's video quality by using VP9

### PR DESCRIPTION
**Pull request by coreequip**
Less blurry and more crisp video on chrome (and maybe safari) by preferring the VP9 codec.

### CODE REVIEW

**Comment by jmattheis** [comment]
Using video/vp9 drastically reduces the frame rate on my Linux machine. I don't know if I want that as default. 

Top is video/VP9; bottom is default / video/VP8

https://user-images.githubusercontent.com/14895212/178308747-bae00d01-3a48-4cbc-8739-c78a6024d859.mp4

**Comment by coreequip** [comment]
Yes, that's true. But it keeps the image crisp. When you scroll in source code VP8 blurs ("artefacts") the image. This may be okay for video game streaming but fails on viewing code. Would you consider this as an option? Like "less FPS but more quality"?

**Comment by jmattheis** [comment]
Yes, I'm okay with a setting, but I'm unsure if we should put it into the triple dot menu or open another menu when the start presentation button is clicked.

**Comment by coreequip** [comment]
> or open another menu when the start presentation button is clicked.

Well, this will be a UX hell. 😈

**Comment by jmattheis** [comment]
Done via db0a180b2ede6fe3c53058ef453f1c5691fb0b45

**Pull request closed without merging**
